// <auto-generated />
using HistoricoClimatologico.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HistoricoClimatologico.Database.Migrations
{
    [DbContext(typeof(HistoricoClimatologicoContext))]
    [Migration("20200426232919_AdicionarCampos")]
    partial class AdicionarCampos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("HistoricoClimatologico.Database.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoCidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Data")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCidade")
                        .HasColumnType("TEXT");

                    b.Property<float>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<int>("Timezone")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Umidade")
                        .HasColumnType("REAL");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
